name: Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: aalmiray/gradle-tests
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
        
      - name: Commit
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo $VERSION > VERSION
          git add VERSION
          git config --global user.email "jreleaser@kordamp.org"
          git config --global user.name "jreleaserbot"
          git commit -a -m "Releasing version $VERSION"
          git push origin master
